routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Admin controllers
use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PersonController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AnalyticsController;

// Front controllers
use App\Http\Controllers\Front\FrontController;
use App\Http\Controllers\Front\CommentController as Comment_Controller;
use App\Http\Controllers\Front\ProfileController;
use App\Http\Controllers\AuthController;


Route::view('/test', 'front.test')->name('test');

Route::get('/', [FrontController::class, 'homepage'])->name('home');


// ADMIN routes ----------------------------------------

Route::prefix('admin')
    ->middleware(['auth', 'admin', 'verified'])
    ->name('admin.')
    ->group(function () {
      
  Route::view('/', 'admin.home')->name('home');
  
  Route::resources([
    'authors' => AuthorController::class,
    'articles' => ArticleController::class,
    'categories' => CategoryController::class,
    'comments' => CommentController::class,
    'configs' => ConfigController::class,
    'images' => ImageController::class,
    'pages' => PageController::class,
    'people' => PersonController::class,
    'roles' => RoleController::class,
    'tags' => TagController::class,
    'users' => UserController::class,
  ]);
  
  // Other comment routes
  Route::prefix('comments')->name('comments.')->group(function () {
    Route::get('soft-deleted/{id}', [CommentController::class, 'showSoftDeleted'])->name('soft-deleted.show');
    Route::delete('force-delete/{id}', [CommentController::class, 'forceDelete'])->name('force-delete');
    Route::patch('{comment}/approve', [CommentController::class, 'approve'])->name('approve');
    Route::patch('{comment}/reject', [CommentController::class, 'reject'])->name('reject');
  });
  
  // Other article routes
  Route::prefix('articles')->name('articles.')->group(function () {
    Route::patch('{article}/publish', [ArticleController::class, 'publish'])->name('publish');
    Route::patch('{article}/hide', [ArticleController::class, 'hide'])->name('hide');
  });  
  
  Route::prefix('analytics')->name('analytics.')->group(function () {
    Route::get('/', [AnalyticsController::class, 'index'])->name('index');
    Route::get('save-request-logs', [AnalyticsController::class, 'saveYesterdaysRequestLogsToDatabase'])->name('saveRequestLogs');
  });
  
});

// AUTH routes ----------------------------------------

Route::view('inscription', 'auth.register')->name('register');
Route::post('inscription', [AuthController::class, 'register']);
Route::view('connexion', 'auth.login')->name('login');
Route::post('connexion', [AuthController::class, 'login']);
Route::post('deconnexion', [AuthController::class, 'logout'])
    ->middleware(['auth'])
    ->name('logout');

// Password reset
Route::name('password.')
    ->middleware(['guest'])
    ->group(function () {
  Route::view('mot-de-passe-oublie', 'auth.forgot-password')->name('request');
  Route::post('mot-de-passe-oublie', [AuthController::class, 'forgotPassword'])->name('email');
  Route::view('/reset-password/{token}', 'auth.reset-password')->name('reset');
  Route::post('/reset-password', [AuthController::class, 'resetPassword'])->name('update');
});

// Email verification
Route::name('verification.')
    ->middleware(['auth'])
    ->group(function () {
      
      // displays a notice to unverified users trying to access restricted areas
      Route::view('/email/verify', 'auth.verify-email')
          ->name('notice');

      // handles requests generated when the user clicks the email verification link in the email
      Route::get('/email/verify/{id}/{hash}', [AuthController::class, 'verifyEmail'])
          ->middleware(['signed', 'throttle:6,1'])
          ->name('verify');

      // resends a verification link
      Route::post('/email/verification-notification', [AuthController::class, 'resendEmailVerificationLink'])
          ->middleware(['throttle:6,1'])
          ->name('send');
});

// FRONT ROUTES ----------------------------------------

// User profile
Route::prefix('compte')
    ->middleware(['auth'])
    ->name('profile.')
    ->group(function () {
      
  Route::view('/', 'front.profile.index')->name('index');
  
  // update user's info
  Route::view('/modifier', 'front.profile.edit')->name('info.edit');
  Route::put('/modifier', [ProfileController::class, 'updateInfo'])->name('info.update');
  
  // delete account
  Route::view('/supprimer-mon-compte', 'front.profile.delete')->name('delete');
  Route::delete('/supprimer-mon-compte', [ProfileController::class, 'destroy']);
  
  // update user's password
  Route::name('password.')->group(function () {
    Route::view('modifier-mot-de-passe', 'front.profile.edit-password')->name('edit');
    Route::put('modifier-mot-de-passe', [ProfileController::class, 'updatePassword'])->name('update');
  });
  
  // show user's comments
  Route::get('commentaires', [ProfileController::class, 'commentsIndex'])->name('comments');
  
  
});



Route::prefix('qui')
    ->name('people.')
    ->group(function () {
      Route::get('/', [FrontController::class, 'peopleIndex'])->name('index');
      Route::get('{person:slug}', [FrontController::class, 'peopleShow'])->name('show');
});

  // static pages

Route::get('/a-propos', [FrontController::class, 'about'])->name('about');
Route::get('/contact', [FrontController::class, 'contact'])->name('contact');
Route::get('/mentions-legales', [FrontController::class, 'legal'])->name('legal');
Route::get('/confidentialite', [FrontController::class, 'privacy'])->name('privacy');
Route::get('/charte-commentaires', [FrontController::class, 'commentRules'])->name('comment-rules');

Route::get('/dernieres-nouvelles', [FrontController::class, 'latestNews'])->name('latestNews');

  // other
Route::get('{year}/{month}/{day}/{slug}', [FrontController::class, 'article'])
  ->where(['year' => '^(19|20)\d{2}$', 'month' => '^(0|[1-9][0-9]{0,1})$', 'day' => '^(0|[1-9][0-9]{0,1})$'])
  ->name('article.show');

Route::get('tag/{tag:slug}', [FrontController::class, 'tag'])->name('tag.show');
Route::get('categorie/{category:slug}', [FrontController::class, 'category'])->name('category.show');
Route::get('auteur/{author:slug}', [FrontController::class, 'author'])->name('author.show');

// Front comments routes
Route::prefix('c')
    ->name('comment.')
    ->group(function () {
      
  Route::post('article/{article:key}', [Comment_Controller::class, 'store'])->name('store');
  
  Route::get('{comment:key}/modifier', [Comment_Controller::class, 'edit'])
      ->middleware('can:update,comment')
      ->name('edit');
  
  Route::patch('{comment:key}', [Comment_Controller::class, 'update'])
      ->middleware('can:update,comment')
      ->name('update');
  
  Route::delete('{comment:key}', [Comment_Controller::class, 'destroy'])
      ->middleware('can:delete,comment')
      ->name('delete');
  
});

app/Http/Controllers/Front/CommentController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;

use App\Models\Comment;
use App\Models\Article;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;

class CommentController extends Controller
{
 /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
  //
  }

 /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
  //
  }

 /**
  * Store a newly created resource in storage.
  *
  * @param  \App\Models\Article  $article
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Article $article, Request $request)
  {  
    $request->validate([
      'content' => 'required|string|max:10000',
    ]);
    
    // generates a unique key for the comment
    $key = Str::random(11);
    $picked = Comment::all()->pluck('key')->toArray();
    while (in_array($key, $picked)) {
      $key = Str::random(11);
    }
    
    Comment::create([
      'key' => $key,
      'user_id' => Auth::id(),
      'article_id' => $article->id,
      'content' => $request->input('content'),
      'status' => 'pending',
    ]);
    
    return back()->with('notification', 'Commentaire en attente de modération');
  }

 /**
  * Display the specified resource.
  *
  * @param  \App\Models\Comment  $comment
  * @return \Illuminate\Http\Response
  */
  public function show(Comment $comment)
  {
  //
  }

 /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Models\Comment  $comment
  * @return \Illuminate\Http\Response
  */
  public function edit(Comment $comment)
  {
    // a middleware already checked if the authenticated user can edit this comment
    
    return view('front.comment.edit')->with([
      'comment' => $comment,
    ]);
  }

 /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Models\Comment  $comment
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, Comment $comment)
  {
    // a middleware already checked if the authenticated user can update this comment
      
    $request->validate([
      'content' => 'required|string|max:10000',
    ]);
    
    $comment->update([
      'status' => 'pending',
      'content' => $request->input('content'),
    ]);
    
    return redirect()->route('article.show', ['year' => $comment->article->created_at->year, 'month' => $comment->article->created_at->month, 'day' => $comment->article->created_at->day, 'slug' => $comment->article->slug])
    ->with('notification', 'Commentaire en attente de modération'); // return view with message
  }

 /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Models\Comment  $comment
  * @return \Illuminate\Http\Response
  */
  public function destroy(Comment $comment)
  {
    // update resource status
    $comment->status = 'deleted';
    $comment->save();
    
    $comment->delete();
    return redirect()->route('article.show', ['year' => $comment->article->created_at->year, 'month' => $comment->article->created_at->month, 'day' => $comment->article->created_at->day, 'slug' => $comment->article->slug])
    ->with('notification', 'Commentaire supprimé');
  }
}

app/Http/Controllers/Front/FrontController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Models\Article;
use App\Models\Tag;
use App\Models\Category;
use App\Models\Author;
use App\Models\Config;
use App\Models\Person;
use App\Models\Page;
use App\Models\Comment;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class FrontController extends Controller
{  
  public function homepage(Request $request)
  {
    // hmArticle = Headline Main Article
    $mainBlockArticleId = Config::where('name', 'main-block-article')->firstOrFail();
    $hmArticle = Article::where('id', $mainBlockArticleId->value)->firstOrFail();
    
    $miniViewArticle1Id = Config::where('name', 'mini-view-article-1')->firstOrFail();
    $headlineSideArticle1 = Article::where('id', $miniViewArticle1Id->value)->firstOrFail();
    
    $miniViewArticle2Id = Config::where('name', 'mini-view-article-2')->firstOrFail();
    $headlineSideArticle2 = Article::where('id', $miniViewArticle2Id->value)->firstOrFail();
    
    $miniViewArticle3Id = Config::where('name', 'mini-view-article-3')->firstOrFail();
    $headlineSideArticle3 = Article::where('id', $miniViewArticle3Id->value)->firstOrFail();
    
    $miniViewArticle4Id = Config::where('name', 'mini-view-article-4')->firstOrFail();
    $headlineSideArticle4 = Article::where('id', $miniViewArticle4Id->value)->firstOrFail();
    
    $headlineSideArticles = collect([
      $headlineSideArticle1,
      $headlineSideArticle2,
      $headlineSideArticle3,
      $headlineSideArticle4
    ]);
        
    return view('front.home')->with([
      'hmArticle' => $hmArticle,
      'headlineSideArticles' => $headlineSideArticles,
      'articles' => Article::public()->orderByDesc('created_at')->take(10)->get(),
    ]);
  }
  
  public function article($year, $month, $day, $slug)
  {
    $article = Article::where('slug', $slug)
                          ->whereYear('created_at', $year)
                          ->whereMonth('created_at', $month)
                          ->whereDay('created_at', $day)
                          ->firstOrFail();
    
    $recentArticles = Article::public()
                            ->where('id', '!=', $article->id)
                            ->latest()
                            ->take(3)
                            ->get();
                          
    return view('front.article')->with([
      'article' => $article,
      'contentInHtml' => Str::of($article->content)->markdown(),
      'recentArticles' => $recentArticles,
      'comments' => Comment::where('article_id', $article->id)
                                ->approved()
                                ->orderByDesc('updated_at')
                                ->get(),
    ]);
  }
  
  public function tag(Tag $tag)
  {
    return view('front.tag')->with([
      'tag' => $tag,
      'articles' => $tag->publicArticles()->paginate(10),
    ]);
  }
  
  public function category(Category $category)
  {
    return view('front.category')->with([
      'category' => $category,
      'articles' => $category->publicArticles()->paginate(10),
    ]);
  }
  
  public function author(Author $author)
  {
    return view('front.author')->with([
      'author' => $author,
      'articles' => $author->publicArticles()->paginate(10),
    ]);
  }
  
  public function peopleIndex()
  {
    return view('front.people.index')->with([
      'people' => Person::all(),
    ]);
  }
  
  public function peopleShow(Person $person)
  {
    return view('front.people.show')->with([
      'person' => $person
    ]);
  }
  
  public function latestNews()
  {
    return view('front.latest-news')->with([
      'articles' => Article::public()->orderByDesc('created_at')->paginate(15),
    ]);
  }
  
  public function about()
  {
    return view('front.page')->with([
      'page' => Page::where('id', 1)->first(),
    ]);
  }
  
  public function contact()
  {
    return view('front.page')->with([
      'page' => Page::where('id', 2)->first(),
    ]);
  }
  
  public function legal()
  {
    return view('front.page')->with([
      'page' => Page::where('id', 3)->first(),
    ]);
  }
  
  public function privacy()
  {
    return view('front.page')->with([
      'page' => Page::where('id', 4)->first(),
    ]);
  }
  
  public function commentRules()
  {
    return view('front.page')->with([
      'page' => Page::where('id', 5)->first(),
    ]);
  }
  
  
}

app/Http/Controllers/Front/ProfileController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Actions\Fortify\UpdateUserProfileInformation;
use App\Actions\Fortify\UpdateUserPassword;


class ProfileController extends Controller
{  
  public function updateInfo(Request $request)
  {
    // retrieves the authenticated user
    $user = Auth::user();
    
    // check if the email was changed
    $emailChanged = false;
    if ($request->input('email') !== $user->email) {
      $emailChanged = true;
    }
        
    // updates this user's name and/or email using Fortify's UpdateUserProfileInformation action
    $UpdateUserProfileInformation = new UpdateUserProfileInformation();
    $UpdateUserProfileInformation->update($user, $request->only(['name', 'email']));
    
    // redirect with relevant message
    if ($emailChanged) {
      return redirect()->route('profile.index')
      ->with('notification', 'Veuillez vérifier votre nouvelle adresse email avec le lien que nous venons de vous envoyer.');
    } else {
      return redirect()->route('profile.index')
      ->with('notification', 'Profil mis à jour correctement');
    }
  }
  
  public function updatePassword(Request $request)
  {
    $UpdateUserPassword = new UpdateUserPassword();
    $UpdateUserPassword->update(Auth::user(), $request->all());
    return redirect()->route('profile.index')
    ->with('notification', 'Mot de passe modifié correctement');
  }
  
  public function destroy()
  {
    Auth::user()->delete();
    return redirect()->route('home')
    ->with('notification', 'Votre compte a bien été supprimé');
  }
  
  public function commentsIndex()
  {
    return view('front.profile.comments')->with([      
      'comments' => Auth::user()->comments()->orderByDesc('updated_at')->paginate(20),
    ]);
  }
}

resources/views/front/profile/comments.blade.php
@extends('layouts.front')

@section('title', 'Commentaires')

@section('content')
  <h1 class="h2 mb-3">Commentaires</h1>
  
  
  @php
    $count = Auth::user()->comments->count();
  @endphp
  
  @if ($count == 0)
    <p>Vous n'avez encore publié aucun commentaire</p>
  @else
    <div class="mb-3">{{ $count }} commentaires</div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Commentaire</th>
          <th scope="col">Date</th>
          <th scope="col">Statut</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($comments as $comment)
          <tr>
            <td>
              <div class="mb-2">
                {{ $comment->content }}
              </div>
              <div class="">
                sur l'article <a class="link-primary" href="{{ route('article.show', ['year' => $comment->article->created_at->year, 'month' => $comment->article->created_at->month, 'day' => $comment->article->created_at->day, 'slug' => $comment->article->slug]) }}">{{ $comment->article->title }}</a>
              </div>
            </td>
            <td>{{ $comment->created_at }}</td>
            <td>@php
                switch ($comment->status) {
                  case 'pending':
                    echo 'en attente de validation';
                    break;
                  case 'approved':
                    echo 'approuvé';
                    break;
                  case 'rejected':
                    echo 'refusé';
                    break;
                }
              @endphp</td>
            <td>
              <ul>
                <li><a class="link-primary" href="{{ route('comment.edit', ['comment' => $comment]) }}">Modifier</a></li>
                <li><a class="link-primary" href="{{ route('comment.delete', ['comment' => $comment]) }}" onclick="event.preventDefault(); 
                  document.getElementById('destroy-form-{{ $comment->id }}').submit();">Supprimer</a></li>
                <form id="destroy-form-{{ $comment->id }}" action="{{ route('comment.delete', ['comment' => $comment]) }}" method="POST" class="hidden">
                  @method('DELETE')
                  @csrf
                </form>
              </ul>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
    {{ $comments->links() }}
  @endif
  
  
@endsection

resources/views/front/profile/delete.blade.php
@extends('layouts.front')

@section('title', 'Mon compte')

@section('content')
  <h1 class="h2 mb-5">Supprimer mon compte</h1>
  
  <div class="alert alert-danger" role="alert">
    <div>
      Attention, cette action est irréversible ! Êtes-vous certain de vouloir supprimer votre compte ?
    </div>
    <div class="text-center">
      <a class="" href="{{ route('profile.delete') }}" onclick="event.preventDefault(); 
        document.getElementById('destroy-form').submit();">SUPPRIMER MON COMPTE</a>
    </div>
    
  </div>
  
  
  <form id="destroy-form" action="{{ route('profile.delete') }}" method="POST" class="hidden alert-link">
    @method('DELETE')
    @csrf
  </form>
  
@endsection

resources/views/front/profile/edit-password.blade.php
@extends('layouts.front')

@section('title', 'Modifier mon mot de passe')

@section('content')
  
  @php
    $hasBagCurrentPassword = false;
    $hasBagPassword = false;
    
    if ($errors->hasBag('updatePassword')) {
      $hasBagCurrentPassword = !empty($errors->updatePassword->first('current_password')) ? true : false;
      $hasBagPassword = !empty($errors->updatePassword->first('password')) ? true : false;
    }
  @endphp
  
  <h1 class="h2">Modifier mon mot de passe</h1>
  <form method="POST" action="{{ route('profile.password.update') }}">
    @csrf
    @method('PUT')
    
    <div class="mb-3">
      <label for="current_password" class="form-label">Mot de passe actuel</label>
      <input name="current_password" type="password" @class([
        'form-control',
        'is-invalid' => $hasBagCurrentPassword,
        ]) id="current_password">
      @error('current_password', 'updatePassword')
        <div class="invalid-feedback">{{ $message }}</div>
      @enderror
    </div>
    
    <div class="mb-3">
      <label for="password" class="form-label">Nouveau mot de passe</label>
      <input name="password" type="password" @class([
        'form-control',
        'is-invalid' => $hasBagPassword,
        ]) id="password">
      @error('password', 'updatePassword')
        <div class="invalid-feedback">{{ $message }}</div>
      @enderror
    </div>
    
    <div class="mb-3">
      <label for="password_confirmation" class="form-label">Confirmer le nouveau mot de passe</label>
      <input name="password_confirmation" type="password" class="form-control" id="password_confirmation">
    </div>
    
    <button type="submit" class="button">Envoyer</button>
  </form>

@endsection

resources/views/front/profile/edit.blade.php
@extends('layouts.front')

@section('title', 'Modifier mon profil')

@section('content')
  
  @php
    $hasBagName = false;
    $hasBagEmail = false;
    
    if ($errors->hasBag('updateProfileInformation')) {
      $hasBagName = !empty($errors->updateProfileInformation->first('name')) ? true : false;
      $hasBagEmail = !empty($errors->updateProfileInformation->first('email')) ? true : false;
    }
  @endphp
  
  <h1 class="h2">Modifier mon profil</h1>
  <form method="POST" action="{{ route('profile.info.update') }}">
    @csrf
    @method('PUT')
    
    <div class="mb-3">
      <label for="name" class="form-label">Nom</label>
      <input name="name" type="text" @class([
        'form-control',
        'is-invalid' => $errors->has('name') || $hasBagName,
        ]) id="name" value="{{ auth()->user()->name }}">
      @error ('name', 'updateProfileInformation')
        <div class="invalid-feedback">{{ $errors->updateProfileInformation->first('name') }}</div>
      @enderror
    </div>
    
    <div class="mb-3">
      <label for="email" class="form-label">Email</label>
      <input name="email" type="email" @class([
        'form-control',
        'is-invalid' => $errors->has('email') || $hasBagEmail,
        ]) id="email" value="{{ auth()->user()->email }}">
      @error ('email', 'updateProfileInformation')
        <div class="invalid-feedback">{{ $errors->updateProfileInformation->first('email') }}</div>
      @enderror
    </div>
    
    <button type="submit" class="button">Modifier</button>
  </form>

@endsection

resources/views/front/profile/index.blade.php
@extends('layouts.front')

@section('title', 'Mon compte')

@section('content')
  <h1 class="h2">Mon compte</h1>
  
  @if (!Auth::user()->hasVerifiedEmail())
    <div class="alert alert-warning" role="alert">
      Vous n'avez pas encore vérifié votre email. <a class="alert-link" href="{{ route('verification.send') }}" onclick="event.preventDefault(); document.getElementById('send-verification-link-form').submit();">Besoin d'un nouveau lien ?</a>
    </div>
    <form id="send-verification-link-form" action="{{ route('verification.send') }}" method="POST">
      @csrf
    </form>
  @endif
  
  <div class="row align-items-center mt-4">
    <div class="col-9">
      <h2 class="h3">Profil</h2>
    </div>
    <div class="col-3 text-end">
      <div class="">
        <a href="{{ route('profile.info.edit') }}" class="button">Modifier</a>
      </div>
      
    </div>
  </div>
  
  <ul>
    <li>Nom : {{ Auth::user()->name }}</li>
    <li>Email : {{ Auth::user()->email }}</li>
    <li>Compte créé le : {{ Auth::user()->created_at->format('d/m/Y') }}</li>
  </ul>
  
  <h2 class="h3">Compte</h2>
  <ul>
    <li><a class="link-primary" href="{{ route('profile.password.edit') }}">Modifier mon mot de passe</a></li>
    <li><a class="link-primary" href="{{ route('profile.delete') }}">Supprimer mon compte</a></li>
  </ul>
  
  <h2 class="h3">Commentaires</h2>
  <ul>
    <li><a class="link-primary" href="{{ route('profile.comments') }}">Liste de mes commentaires</a> <span>({{ Auth::user()->comments->count() }})</span></li>
  </ul>
  
@endsection