routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Admin controllers
use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PersonController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AnalyticsController;

// Front controllers
use App\Http\Controllers\Front\FrontController;
use App\Http\Controllers\Front\CommentController as Comment_Controller;
use App\Http\Controllers\Front\ProfileController;
use App\Http\Controllers\AuthController;


Route::view('/test', 'front.test')->name('test');

Route::get('/', [FrontController::class, 'homepage'])->name('home');


// ADMIN routes ----------------------------------------

Route::prefix('admin')
    ->middleware(['auth', 'admin', 'verified'])
    ->name('admin.')
    ->group(function () {
      
  Route::view('/', 'admin.home')->name('home');
  
  Route::resources([
    'authors' => AuthorController::class,
    'articles' => ArticleController::class,
    'categories' => CategoryController::class,
    'comments' => CommentController::class,
    'configs' => ConfigController::class,
    'images' => ImageController::class,
    'pages' => PageController::class,
    'people' => PersonController::class,
    'roles' => RoleController::class,
    'tags' => TagController::class,
    'users' => UserController::class,
  ]);
  
  // Other comment routes
  Route::prefix('comments')->name('comments.')->group(function () {
    Route::get('soft-deleted/{id}', [CommentController::class, 'showSoftDeleted'])->name('soft-deleted.show');
    Route::delete('force-delete/{id}', [CommentController::class, 'forceDelete'])->name('force-delete');
    Route::patch('{comment}/approve', [CommentController::class, 'approve'])->name('approve');
    Route::patch('{comment}/reject', [CommentController::class, 'reject'])->name('reject');
  });
  
  // Other article routes
  Route::prefix('articles')->name('articles.')->group(function () {
    Route::patch('{article}/publish', [ArticleController::class, 'publish'])->name('publish');
    Route::patch('{article}/hide', [ArticleController::class, 'hide'])->name('hide');
  });  
  
  Route::prefix('analytics')->name('analytics.')->group(function () {
    Route::get('/', [AnalyticsController::class, 'index'])->name('index');
    Route::get('save-request-logs', [AnalyticsController::class, 'saveYesterdaysRequestLogsToDatabase'])->name('saveRequestLogs');
  });
  
});

// AUTH routes ----------------------------------------

Route::view('inscription', 'auth.register')->name('register');
Route::post('inscription', [AuthController::class, 'register']);
Route::view('connexion', 'auth.login')->name('login');
Route::post('connexion', [AuthController::class, 'login']);
Route::post('deconnexion', [AuthController::class, 'logout'])
    ->middleware(['auth'])
    ->name('logout');

// Password reset
Route::name('password.')
    ->middleware(['guest'])
    ->group(function () {
  Route::view('mot-de-passe-oublie', 'auth.forgot-password')->name('request');
  Route::post('mot-de-passe-oublie', [AuthController::class, 'forgotPassword'])->name('email');
  Route::view('/reset-password/{token}', 'auth.reset-password')->name('reset');
  Route::post('/reset-password', [AuthController::class, 'resetPassword'])->name('update');
});

// Email verification
Route::name('verification.')
    ->middleware(['auth'])
    ->group(function () {
      
      // displays a notice to unverified users trying to access restricted areas
      Route::view('/email/verify', 'auth.verify-email')
          ->name('notice');

      // handles requests generated when the user clicks the email verification link in the email
      Route::get('/email/verify/{id}/{hash}', [AuthController::class, 'verifyEmail'])
          ->middleware(['signed', 'throttle:6,1'])
          ->name('verify');

      // resends a verification link
      Route::post('/email/verification-notification', [AuthController::class, 'resendEmailVerificationLink'])
          ->middleware(['throttle:6,1'])
          ->name('send');
});

// FRONT ROUTES ----------------------------------------

// User profile
Route::prefix('compte')
    ->middleware(['auth'])
    ->name('profile.')
    ->group(function () {
      
  Route::view('/', 'front.profile.index')->name('index');
  
  // update user's info
  Route::view('/modifier', 'front.profile.edit')->name('info.edit');
  Route::put('/modifier', [ProfileController::class, 'updateInfo'])->name('info.update');
  
  // delete account
  Route::view('/supprimer-mon-compte', 'front.profile.delete')->name('delete');
  Route::delete('/supprimer-mon-compte', [ProfileController::class, 'destroy']);
  
  // update user's password
  Route::name('password.')->group(function () {
    Route::view('modifier-mot-de-passe', 'front.profile.edit-password')->name('edit');
    Route::put('modifier-mot-de-passe', [ProfileController::class, 'updatePassword'])->name('update');
  });
  
  // show user's comments
  Route::get('commentaires', [ProfileController::class, 'commentsIndex'])->name('comments');
  
  
});



Route::prefix('qui')
    ->name('people.')
    ->group(function () {
      Route::get('/', [FrontController::class, 'peopleIndex'])->name('index');
      Route::get('{person:slug}', [FrontController::class, 'peopleShow'])->name('show');
});

  // static pages

Route::get('/a-propos', [FrontController::class, 'about'])->name('about');
Route::get('/contact', [FrontController::class, 'contact'])->name('contact');
Route::get('/mentions-legales', [FrontController::class, 'legal'])->name('legal');
Route::get('/confidentialite', [FrontController::class, 'privacy'])->name('privacy');
Route::get('/charte-commentaires', [FrontController::class, 'commentRules'])->name('comment-rules');

Route::get('/dernieres-nouvelles', [FrontController::class, 'latestNews'])->name('latestNews');

  // other
Route::get('{year}/{month}/{day}/{slug}', [FrontController::class, 'article'])
  ->where(['year' => '^(19|20)\d{2}$', 'month' => '^(0|[1-9][0-9]{0,1})$', 'day' => '^(0|[1-9][0-9]{0,1})$'])
  ->name('article.show');

Route::get('tag/{tag:slug}', [FrontController::class, 'tag'])->name('tag.show');
Route::get('categorie/{category:slug}', [FrontController::class, 'category'])->name('category.show');
Route::get('auteur/{author:slug}', [FrontController::class, 'author'])->name('author.show');

// Front comments routes
Route::prefix('c')
    ->name('comment.')
    ->group(function () {
      
  Route::post('article/{article:key}', [Comment_Controller::class, 'store'])->name('store');
  
  Route::get('{comment:key}/modifier', [Comment_Controller::class, 'edit'])
      ->middleware('can:update,comment')
      ->name('edit');
  
  Route::patch('{comment:key}', [Comment_Controller::class, 'update'])
      ->middleware('can:update,comment')
      ->name('update');
  
  Route::delete('{comment:key}', [Comment_Controller::class, 'destroy'])
      ->middleware('can:delete,comment')
      ->name('delete');
  
});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

class Comment extends Model
{
  use HasFactory, SoftDeletes;
  
  protected $fillable = ['key', 'user_id', 'article_id', 'content', 'status'];
  
  public function author()
  {
    return $this->belongsTo(User::class, 'user_id');
  }
  
  public function article()
  {
    return $this->belongsTo(Article::class);
  }
  
  public function createdAtDifference()
  {
    return Carbon::parse($this->created_at)->locale('fr')->diffForHumans();
  }
  
  public function wasModified()
  {
    return $this->created_at != $this->updated_at ? true : false;
  }
  
  // Local scopes
  public function scopePending($query)
  {
    return $query->where('status', 'pending');
  }
  
  public function scopeApproved($query)
  {
    return $query->where('status', 'approved');
  }
  
  public function scopeRejected($query)
  {
    return $query->where('status', 'rejected');
  }
  
  public function scopeDeleted($query)
  {
    return $query->where('status', 'deleted');
  }  
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use Illuminate\Http\Request;

use App\Http\Requests\StoreCommentRequest;
use App\Http\Requests\UpdateCommentRequest;
use Illuminate\Support\Str;
use App\Events\CommentApprovedEvent;
use App\Events\CommentRejectedEvent;
use App\Events\CommentDestroyedEvent;


class CommentController extends Controller
{
  public function index()
  {
    return view('admin.comments.index')->with([
      'pending' => Comment::pending()->orderByDesc('updated_at')->get(),
      'comments' => Comment::withTrashed()->orderByDesc('id')->paginate(20),
    ]);
  }

  public function create()
  {
    // generates a unique key for the comment
    $key = Str::random(11);
    $picked = Comment::all()->pluck('key')->toArray();
    while (in_array($key, $picked)) {
      $key = Str::random(11);
    }
    
    return view('admin.comments.create')->with([
      'key' => $key,
      'comment' => new Comment(), // passes an empty model to the view
    ]);
  }

  public function store(StoreCommentRequest $request)
  {
    $validatedData = array_merge($request->validated(), [
      'status' => 'pending',
    ]);
    
    Comment::create($validatedData);
    
    return redirect()->route('admin.comments.index')
    ->with('message', 'Comment created successfully.');
  }

  public function show(Comment $comment)
  {
    return view('admin.comments.show')->with([
      'comment' => $comment,
    ]);
  }

  public function edit(Comment $comment)
  {
    return view('admin.comments.edit')->with([
      'comment' => $comment,
    ]);
  }

  public function update(UpdateCommentRequest $request, Comment $comment)
  {
    $comment->update($request->validated()); // update model
    return redirect()->route('admin.comments.show', ['comment' => $comment])
    ->with('message', 'Comment updated successfully.'); // return view with message
  }

  public function destroy(Comment $comment)
  {
    $id = $comment->id;
    
    // update resource status
    $comment->status = 'deleted';
    $comment->save();
    
    $comment->delete();
    
    CommentDestroyedEvent::dispatch($id);
    
    return redirect()->route('admin.comments.index')
    ->with('message', 'Comment SOFT deleted successfully.');
  }
  
  public function showSoftDeleted($id)
  {
    $comment = Comment::withTrashed()
                    ->where('id', $id)
                    ->firstOrFail();
    
    return view('admin.comments.show')->with([
      'comment' => $comment,
    ]);
  }
  
   public function forceDelete($id)
   {     
     $comment = Comment::withTrashed()
                     ->where('id', $id)
                     ->firstOrFail();
     
     $comment->forceDelete();
     return redirect()->route('admin.comments.index')
     ->with('message', 'Comment FORCE deleted successfully.');
   }
   
   public function approve(Comment $comment)
   {
     $comment->status = 'approved';
     $comment->save();
     
     // send a email to notify the user
     CommentApprovedEvent::dispatch($comment);
     
     return redirect()->route('admin.comments.index')
     ->with('message', 'Comment approved');
   }
   
   public function reject(Comment $comment)
   {
     $comment->status = 'rejected';
     $comment->save();
     
     // send a email to notify the user
     CommentRejectedEvent::dispatch($comment);
     
     return redirect()->route('admin.comments.index')
     ->with('message', 'Comment rejected');
   }
}

app/Http/Controllers/Front/CommentController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;

use App\Models\Comment;
use App\Models\Article;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;

class CommentController extends Controller
{
 /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
  //
  }

 /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
  //
  }

 /**
  * Store a newly created resource in storage.
  *
  * @param  \App\Models\Article  $article
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Article $article, Request $request)
  {  
    $request->validate([
      'content' => 'required|string|max:10000',
    ]);
    
    // generates a unique key for the comment
    $key = Str::random(11);
    $picked = Comment::all()->pluck('key')->toArray();
    while (in_array($key, $picked)) {
      $key = Str::random(11);
    }
    
    Comment::create([
      'key' => $key,
      'user_id' => Auth::id(),
      'article_id' => $article->id,
      'content' => $request->input('content'),
      'status' => 'pending',
    ]);
    
    return back()->with('notification', 'Commentaire en attente de modération');
  }

 /**
  * Display the specified resource.
  *
  * @param  \App\Models\Comment  $comment
  * @return \Illuminate\Http\Response
  */
  public function show(Comment $comment)
  {
  //
  }

 /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Models\Comment  $comment
  * @return \Illuminate\Http\Response
  */
  public function edit(Comment $comment)
  {
    // a middleware already checked if the authenticated user can edit this comment
    
    return view('front.comment.edit')->with([
      'comment' => $comment,
    ]);
  }

 /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Models\Comment  $comment
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, Comment $comment)
  {
    // a middleware already checked if the authenticated user can update this comment
      
    $request->validate([
      'content' => 'required|string|max:10000',
    ]);
    
    $comment->update([
      'status' => 'pending',
      'content' => $request->input('content'),
    ]);
    
    return redirect()->route('article.show', ['year' => $comment->article->created_at->year, 'month' => $comment->article->created_at->month, 'day' => $comment->article->created_at->day, 'slug' => $comment->article->slug])
    ->with('notification', 'Commentaire en attente de modération'); // return view with message
  }

 /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Models\Comment  $comment
  * @return \Illuminate\Http\Response
  */
  public function destroy(Comment $comment)
  {
    // update resource status
    $comment->status = 'deleted';
    $comment->save();
    
    $comment->delete();
    return redirect()->route('article.show', ['year' => $comment->article->created_at->year, 'month' => $comment->article->created_at->month, 'day' => $comment->article->created_at->day, 'slug' => $comment->article->slug])
    ->with('notification', 'Commentaire supprimé');
  }
}

resources/views/admin/comments/create.blade.php
@extends('layouts.admin')

@section('title', 'Create comment')

@section('content')
  <x-admin-breadcrumb levels=2 label="Comments" label2="Create" link="{{ route('admin.comments.index') }}"/>
  <h1 class="h2">Create new comment</h1>
  <form action="{{ route('admin.comments.store') }}" method="POST">
    <div class="mb-3 row">
      <label for="key" class="col-sm-2 col-form-label">key</label>
      <div class="col-sm-10">
        <input name="key" type="text" readonly class="form-control-plaintext" id="key" value="{{ $key }}">
      </div>
    </div>
    @include('admin.comments.form')
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/admin/comments/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit comment')

@section('content')
  <x-admin-breadcrumb levels=2 label="Comments" label2="Edit" link="{{ route('admin.comments.index') }}"/>
  <h1 class="h2">Edit comment</h1>
  <form action="{{ route('admin.comments.update', ['comment' => $comment]) }}" method="POST">
    @method('PATCH')
    @include('admin.comments.form')
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
@endsection

resources/views/admin/comments/form.blade.php
@csrf

<div class="mb-3">
  <label for="user_id" class="form-label">user_id *</label>
  <input type="text" id="user_id" name="user_id" @class([
    'form-control',
    'is-invalid' => $errors->has('user_id'),
    ]) value="{{ old('user_id') ?? $comment->user_id }}">
  @error('user_id')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="mb-3">
  <label for="article_id" class="form-label">article_id *</label>
  <input type="text" id="article_id" name="article_id" @class([
    'form-control',
    'is-invalid' => $errors->has('article_id'),
    ]) value="{{ old('article_id') ?? $comment->article_id }}">
  @error('article_id')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="mb-3">
  <label for="content" class="form-label">content *</label>
  <textarea @class([
    'form-control',
    'is-invalid' => $errors->has('content'),
    ]) id="content" rows="5" name="content">{{ old('content') ?? $comment->content }}</textarea>
  @error('content')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

resources/views/admin/comments/index.blade.php
@extends('layouts.admin')

@section('title', 'Comments index')

@section('content')
  <x-admin-breadcrumb levels=1 label="Comments" link="{{ route('admin.comments.index') }}"/>
  <x-admin-resource-index-header 
  title="Comments index" 
  route="{{ route('admin.comments.create') }}" 
  btn-text="create new comment"/>
  
  <h2 class="h3 mt-4">Pending comments</h2>
  <table class="table table-hover my-4">
    <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Article</th>
        <th scope="col">Content</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
    @foreach ($pending as $comment)
      <tr>
        <td>
          @if (is_null($comment->author))
            <span class="fw-bold fst-italic">NULL</span>
          @else
            <a href="{{ route('admin.users.show', ['user' => $comment->author]) }}">{{ $comment->author->name }}</a>
          @endif
        </td>
        <td>
          @if (is_null($comment->article))
            <span class="fw-bold fst-italic">NULL</span>
          @else
            <a href="{{ route('admin.articles.show', ['article' => $comment->article]) }}">{{ $comment->article->title }}</a>
          @endif
        </td>
        <td>{{ $comment->content }}</td>
        <td>
          <div class="mb-2">
            <a class="btn btn-success" href="{{ route('admin.comments.approve', ['comment' => $comment]) }}" onclick="event.preventDefault(); 
              document.getElementById('approve-comment-{{ $comment->id }}-form').submit();">approve</a>
            <form id="approve-comment-{{ $comment->id }}-form" action="{{ route('admin.comments.approve', ['comment' => $comment]) }}" method="POST" class="hidden">
              @csrf
              @method('PATCH')
            </form>
          </div>
          <div class="">
            <a class="btn btn-danger" href="{{ route('admin.comments.reject', ['comment' => $comment]) }}" onclick="event.preventDefault(); 
              document.getElementById('reject-comment-{{ $comment->id }}-form').submit();">reject</a>
            <form id="reject-comment-{{ $comment->id }}-form" action="{{ route('admin.comments.reject', ['comment' => $comment]) }}" method="POST" class="hidden">
              @csrf
              @method('PATCH')
            </form>
          </div>
        </td>
      </tr>
    @endforeach
    </tbody>
  </table>
  
  
  <h2 class="h3">All comments</h2>
  <table class="table table-hover mt-4">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">User</th>
        <th scope="col">Article</th>
        <th scope="col">Content</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
    @foreach ($comments as $comment)
      <tr>
        <td>{{ $comment->id }}</td>
        <td>
          @if (is_null($comment->author))
            <span class="fw-bold fst-italic">NULL</span>
          @else
            <a href="{{ route('admin.users.show', ['user' => $comment->author]) }}">{{ $comment->author->name }}</a>
          @endif
        </td>
        <td>
          @if (is_null($comment->article))
            <span class="fw-bold fst-italic">NULL</span>
          @else
            <a href="{{ route('admin.articles.show', ['article' => $comment->article]) }}">{{ $comment->article->title }}</a>
          @endif
        </td>
        <td>{{ $comment->content }}</td>
        <td>{{ $comment->status }}</td>
        <td>
          <a class="btn btn-primary" href="@if (is_null($comment->deleted_at))
            {{ route('admin.comments.show', ['comment' => $comment]) }}
          @else
            {{ route('admin.comments.soft-deleted.show', ['id' => $comment->id]) }}
          @endif">show</a>
          <a class="btn btn-primary" href="{{ route('admin.comments.edit', ['comment' => $comment]) }}">edit</a>
        </td>
      </tr>
    @endforeach
    </tbody>
  </table>
  {{ $comments->links() }}
@endsection

resources/views/admin/comments/show.blade.php
@extends('layouts.admin')

@section('title', 'Show comment')

@section('content')
  <x-admin-breadcrumb levels=2 label="Comments" label2="Show" link="{{ route('admin.comments.index') }}"/>
  <h1 class="h2">Comment id° {{ $comment->id }}</h1>
  
  <div class="btn-group btn-group-lg my-4">
    <a href="{{ route('admin.comments.edit', ['comment' => $comment]) }}" type="button" class="btn btn-primary">EDIT</a>
    @if (is_null($comment->deleted_at))
      <a href="{{ route('admin.comments.destroy', ['comment' => $comment]) }}" type="button" class="btn btn-warning" onclick="event.preventDefault(); 
        document.getElementById('soft-delete-form').submit();">SOFT DELETE</a>
    @endif
    <a href="{{ route('admin.comments.force-delete', ['id' => $comment->id]) }}" type="button" class="btn btn-danger" onclick="event.preventDefault(); 
      document.getElementById('force-delete-form').submit();">FORCE DELETE</a>
  </div>
  <div class="hidden">
    <form id="soft-delete-form" action="{{ route('admin.comments.destroy', ['comment' => $comment]) }}" method="POST">
      @method('DELETE')
      @csrf
    </form>
    <form id="force-delete-form" action="{{ route('admin.comments.force-delete', ['id' => $comment->id]) }}" method="POST">
      @method('DELETE')
      @csrf
    </form>
  </div>
    
  <ul>
    <li><strong>Key:</strong> {{ $comment->key }}</li>
    <li><strong>Status:</strong> {{ $comment->status }}</li>
    <li><strong>created_at:</strong> {{ $comment->created_at }}</li>
    <li><strong>updated_at:</strong> {{ $comment->updated_at }}</li>
    <li><strong>deleted_at:</strong> {{ $comment->deleted_at }}</li>
    <li>
      @if (is_null($comment->author))
        <strong>Author:</strong> <span class="fw-bold fst-italic">NULL</span>
      @else
        <strong>Author:</strong> <a href="{{ route('admin.users.show', ['user' => $comment->author]) }}">{{ $comment->author->name }}</a>
      @endif
    </li>
    <li>
      @if (is_null($comment->article))
        <strong>Article:</strong> <span class="fw-bold fst-italic">NULL</span>
      @else
        <strong>Article:</strong> <a href="{{ route('admin.articles.show', ['article' => $comment->article]) }}">{{ $comment->article->title }}</a>
      @endif
    </li>
    <li><strong>Content:</strong> {{ $comment->content }}</li>
  </ul>
@endsection