routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// Admin controllers
use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PersonController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AnalyticsController;

// Front controllers
use App\Http\Controllers\Front\FrontController;
use App\Http\Controllers\Front\CommentController as Comment_Controller;
use App\Http\Controllers\Front\ProfileController;
use App\Http\Controllers\AuthController;


Route::view('/test', 'front.test')->name('test');

Route::get('/', [FrontController::class, 'homepage'])->name('home');


// ADMIN routes ----------------------------------------

Route::prefix('admin')
    ->middleware(['auth', 'admin', 'verified'])
    ->name('admin.')
    ->group(function () {
      
  Route::view('/', 'admin.home')->name('home');
  
  Route::resources([
    'authors' => AuthorController::class,
    'articles' => ArticleController::class,
    'categories' => CategoryController::class,
    'comments' => CommentController::class,
    'configs' => ConfigController::class,
    'images' => ImageController::class,
    'pages' => PageController::class,
    'people' => PersonController::class,
    'roles' => RoleController::class,
    'tags' => TagController::class,
    'users' => UserController::class,
  ]);
  
  // Other comment routes
  Route::prefix('comments')->name('comments.')->group(function () {
    Route::get('soft-deleted/{id}', [CommentController::class, 'showSoftDeleted'])->name('soft-deleted.show');
    Route::delete('force-delete/{id}', [CommentController::class, 'forceDelete'])->name('force-delete');
    Route::patch('{comment}/approve', [CommentController::class, 'approve'])->name('approve');
    Route::patch('{comment}/reject', [CommentController::class, 'reject'])->name('reject');
  });
  
  // Other article routes
  Route::prefix('articles')->name('articles.')->group(function () {
    Route::patch('{article}/publish', [ArticleController::class, 'publish'])->name('publish');
    Route::patch('{article}/hide', [ArticleController::class, 'hide'])->name('hide');
  });  
  
  Route::prefix('analytics')->name('analytics.')->group(function () {
    Route::get('/', [AnalyticsController::class, 'index'])->name('index');
    Route::get('save-request-logs', [AnalyticsController::class, 'saveYesterdaysRequestLogsToDatabase'])->name('saveRequestLogs');
  });
  
});

// AUTH routes ----------------------------------------

Route::view('inscription', 'auth.register')->name('register');
Route::post('inscription', [AuthController::class, 'register']);
Route::view('connexion', 'auth.login')->name('login');
Route::post('connexion', [AuthController::class, 'login']);
Route::post('deconnexion', [AuthController::class, 'logout'])
    ->middleware(['auth'])
    ->name('logout');

// Password reset
Route::name('password.')
    ->middleware(['guest'])
    ->group(function () {
  Route::view('mot-de-passe-oublie', 'auth.forgot-password')->name('request');
  Route::post('mot-de-passe-oublie', [AuthController::class, 'forgotPassword'])->name('email');
  Route::view('/reset-password/{token}', 'auth.reset-password')->name('reset');
  Route::post('/reset-password', [AuthController::class, 'resetPassword'])->name('update');
});

// Email verification
Route::name('verification.')
    ->middleware(['auth'])
    ->group(function () {
      
      // displays a notice to unverified users trying to access restricted areas
      Route::view('/email/verify', 'auth.verify-email')
          ->name('notice');

      // handles requests generated when the user clicks the email verification link in the email
      Route::get('/email/verify/{id}/{hash}', [AuthController::class, 'verifyEmail'])
          ->middleware(['signed', 'throttle:6,1'])
          ->name('verify');

      // resends a verification link
      Route::post('/email/verification-notification', [AuthController::class, 'resendEmailVerificationLink'])
          ->middleware(['throttle:6,1'])
          ->name('send');
});

// FRONT ROUTES ----------------------------------------

// User profile
Route::prefix('compte')
    ->middleware(['auth'])
    ->name('profile.')
    ->group(function () {
      
  Route::view('/', 'front.profile.index')->name('index');
  
  // update user's info
  Route::view('/modifier', 'front.profile.edit')->name('info.edit');
  Route::put('/modifier', [ProfileController::class, 'updateInfo'])->name('info.update');
  
  // delete account
  Route::view('/supprimer-mon-compte', 'front.profile.delete')->name('delete');
  Route::delete('/supprimer-mon-compte', [ProfileController::class, 'destroy']);
  
  // update user's password
  Route::name('password.')->group(function () {
    Route::view('modifier-mot-de-passe', 'front.profile.edit-password')->name('edit');
    Route::put('modifier-mot-de-passe', [ProfileController::class, 'updatePassword'])->name('update');
  });
  
  // show user's comments
  Route::get('commentaires', [ProfileController::class, 'commentsIndex'])->name('comments');
  
  
});



Route::prefix('qui')
    ->name('people.')
    ->group(function () {
      Route::get('/', [FrontController::class, 'peopleIndex'])->name('index');
      Route::get('{person:slug}', [FrontController::class, 'peopleShow'])->name('show');
});

  // static pages

Route::get('/a-propos', [FrontController::class, 'about'])->name('about');
Route::get('/contact', [FrontController::class, 'contact'])->name('contact');
Route::get('/mentions-legales', [FrontController::class, 'legal'])->name('legal');
Route::get('/confidentialite', [FrontController::class, 'privacy'])->name('privacy');
Route::get('/charte-commentaires', [FrontController::class, 'commentRules'])->name('comment-rules');

Route::get('/dernieres-nouvelles', [FrontController::class, 'latestNews'])->name('latestNews');

  // other
Route::get('{year}/{month}/{day}/{slug}', [FrontController::class, 'article'])
  ->where(['year' => '^(19|20)\d{2}$', 'month' => '^(0|[1-9][0-9]{0,1})$', 'day' => '^(0|[1-9][0-9]{0,1})$'])
  ->name('article.show');

Route::get('tag/{tag:slug}', [FrontController::class, 'tag'])->name('tag.show');
Route::get('categorie/{category:slug}', [FrontController::class, 'category'])->name('category.show');
Route::get('auteur/{author:slug}', [FrontController::class, 'author'])->name('author.show');

// Front comments routes
Route::prefix('c')
    ->name('comment.')
    ->group(function () {
      
  Route::post('article/{article:key}', [Comment_Controller::class, 'store'])->name('store');
  
  Route::get('{comment:key}/modifier', [Comment_Controller::class, 'edit'])
      ->middleware('can:update,comment')
      ->name('edit');
  
  Route::patch('{comment:key}', [Comment_Controller::class, 'update'])
      ->middleware('can:update,comment')
      ->name('update');
  
  Route::delete('{comment:key}', [Comment_Controller::class, 'destroy'])
      ->middleware('can:delete,comment')
      ->name('delete');
  
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Article extends Model
{
  use HasFactory;
  
  protected $fillable = [
    'key',
    'author_id', 
    'category_id',
    'image_id',
    'title', 
    'description', 
    'content', 
    'slug', 
    'public',
    'published_at',
  ];
  
  // get the author that owns the article
  public function author()
  {
    return $this->belongsTo(Author::class);
  }
  
  // get the category that owns the article
  public function category()
  {
    return $this->belongsTo(Category::class);
  }
  
  // get the main image associated with the article
  public function image()
  {
    return $this->belongsTo(Image::class);
  }
  
  // get the tags of the article
  public function tags()
  {
    return $this->belongsToMany(Tag::class)->withTimestamps();
  }
  
  public function comments()
  {
    return $this->hasMany(Comment::class);
  }
  
  public function scopePublic($query)
  {
    return $query->where('public', true);
  }
  
  public function isPublic()
  {
    return $this->public;
  }
  
  public function postedAtDifference()
  {
    return Carbon::parse($this->created_at)->locale('fr')->diffForHumans();
  }
  
  public function postedAtInGoodFrench()
  {
    return $this->created_at->day . ' ' . $this->created_at->locale('fr')->monthName . ' ' . $this->created_at->year;
  }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\Author;
use App\Models\Category;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Http\Requests\StoreArticleRequest;
use App\Http\Requests\UpdateArticleRequest;
use Carbon\Carbon;
use App\Events\ArticleDestroyedEvent;


class ArticleController extends Controller
{
  public function index()
  {
    return view('admin.articles.index')->with([
      'articles' => Article::orderByDesc('id')->paginate(20),
    ]);
  }

  public function create()
  {
    // generates a unique key for the article
    $key = Str::random(11);
    $picked = Article::all()->pluck('key')->toArray();
    while (in_array($key, $picked)) {
      $key = Str::random(11);
    }
    
    return view('admin.articles.create')->with([
      'key' => $key,
      'article' => new Article(),
      'authors' => Author::all(),
      'categories' => Category::all(),
      'tags' => Tag::all(),
    ]);
  }

  public function store(StoreArticleRequest $request)
  {
    $article = Article::create($request->validated()); // create new model with validated data
    $article->tags()->sync($request->input('tags')); // sync article's tags
    return redirect(route('admin.articles.index'))
    ->with('message', 'Article created successfully.'); // return view with message
  }

  public function show(Article $article)
  {
    return view('admin.articles.show')->with([
      'article' => $article,
      'contentInHtml' => Str::of($article->content)->markdown(),
    ]);
  }

  public function edit(Article $article)
  {
    return view('admin.articles.edit')->with([
      'article' => $article,
      'authors' => Author::all(),
      'categories' => Category::all(),
      'tags' => Tag::all(),
    ]);
  }

  public function update(UpdateArticleRequest $request, Article $article)
  {
    $article->update($request->validated()); // update model
    $article->tags()->sync($request->input('tags')); // sync article's tags
    return redirect(route('admin.articles.show', ['article' => $article]))
    ->with('message', 'Article updated successfully.'); // return view with message
  }

  public function destroy(Article $article)
  {
    $id = $article->id;
    
    $article->delete();
    
    ArticleDestroyedEvent::dispatch($id);
    
    return redirect(route('admin.articles.index'))
    ->with('message', 'Article deleted successfully.');
  }
  
  public function publish(Article $article)
  {
    $article->public = true;
    $article->published_at = Carbon::now();
    $article->save();
    
    return redirect(route('admin.articles.show', ['article' => $article]))
    ->with('message', 'Article published successfully'); // return view with message
  }
  
  public function hide(Article $article)
  {
    $article->public = false;
    $article->save();
    
    return redirect(route('admin.articles.show', ['article' => $article]))
    ->with('message', 'Article hidden successfully'); // return view with message
  }
  
}

resources/views/admin/articles/create.blade.php
@extends('layouts.admin')

@section('title', 'Create article')

@section('content')
  <x-admin-breadcrumb levels=2 label="Articles" label2="Create" link="{{ route('admin.articles.index') }}"/>
  <h1 class="h2">Create new article</h1>
  <div class="alert alert-primary my-4" role="alert">
    A slug based on the given title is automatically created when creating a new article. It can be edited afterwards.
  </div>
  <form action="{{ route('admin.articles.store') }}" method="POST">
    <div class="mb-3 row">
      <label for="key" class="col-sm-2 col-form-label">key</label>
      <div class="col-sm-10">
        <input name="key" type="text" readonly class="form-control-plaintext" id="key" value="{{ $key }}">
      </div>
    </div>
    @include('admin.articles.form')
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit article')

@section('content')
  <x-admin-breadcrumb levels=2 label="Articles" label2="Edit" link="{{ route('admin.articles.index') }}"/>
  <h1 class="h2">Edit article</h1>
  <form action="{{ route('admin.articles.update', ['article' => $article]) }}" method="POST">
    @method('PATCH')
    @include('admin.articles.form')
    <div class="mb-3">
      <label for="slug" class="form-label">slug *</label>
      <input type="text" id="slug" name="slug" class="form-control" value="{{ old('slug') ?? $article->slug }}">
      @error('slug')
        <small class="form-text text-muted">{{ $message }}</small>
      @enderror
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
@endsection

resources/views/admin/articles/form.blade.php
@csrf

@error('slug')
  <div class="alert alert-danger mt-3" role="alert">
    <strong>{{ $message }}</strong>
  </div>
@enderror

<div class="mb-3">
  <label class="form-label">author *</label>
  <select @class([
    'form-select',
    'is-invalid' => $errors->has('author_id'),
    ]) name="author_id">
    <option>select author</option>
    @foreach ($authors as $author)
      <option value="{{ $author->id }}" {{ old('author_id') == $author->id || $article->author == $author ? 'selected' : '' }}>{{ $author->name }}</option>
    @endforeach
  </select>
  @error('author_id')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="mb-3">
  <label class="form-label">category *</label>
  <select @class([
    'form-select',
    'is-invalid' => $errors->has('category_id'),
    ]) name="category_id">
    <option>select category</option>
    @foreach ($categories as $category)
      <option value="{{ $category->id }}" {{ old('category_id') == $category->id || $article->category == $category ? 'selected' : '' }}>{{ $category->name }}</option>
    @endforeach
  </select>
  @error('category_id')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="mb-3">
  <label for="image_id" class="form-label">image_id *</label>
  <input type="text" id="image_id" name="image_id" @class([
    'form-control',
    'is-invalid' => $errors->has('image_id'),
    ]) value="{{ old('image_id') ?? $article->image_id }}">
  @error('image_id')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="mb-3">
  <label class="form-label">tags</label>
  <select @class([
    'form-select',
    'is-invalid' => $errors->has('tags'),
    ]) multiple name="tags[]">
    @foreach ($tags as $tag)
      <option 
      value="{{ $tag->id }}"
      {{ !is_null(old('tags')) && in_array($tag->id, old('tags')) || $article->tags->contains($tag) ? 'selected' : '' }}
      >{{ $tag->name }}</option>
    @endforeach
  </select>
  @error('tags')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="mb-3">
  <label for="name" class="form-label">title *</label>
  <input type="text" id="title" name="title" @class([
    'form-control',
    'is-invalid' => $errors->has('title'),
    ]) value="{{ old('title') ?? $article->title }}">
  @error('title')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="mb-3">
  <label for="description" class="form-label">description *</label>
  <textarea @class([
    'form-control',
    'is-invalid' => $errors->has('description'),
    ]) id="description" rows="5" name="description">{{ old('description') ?? $article->description }}</textarea>
  @error('description')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

<div class="mb-3">
  <label for="content" class="form-label">content *</label>
  <textarea @class([
    'form-control',
    'is-invalid' => $errors->has('content'),
    ]) id="content" rows="10" name="content">{{ old('content') ?? $article->content }}</textarea>
  @error('content')
    <div class="invalid-feedback">{{ $message }}</div>
  @enderror
</div>

resources/views/admin/articles/index.blade.php
@extends('layouts.admin')

@section('title', 'Articles index')

@section('content')
  <x-admin-breadcrumb levels=1 label="Articles" link="{{ route('admin.articles.index') }}"/>
  
  <x-admin-resource-index-header 
  title="Articles index" 
  route="{{ route('admin.articles.create') }}" 
  btn-text="create new article"/>
  <table class="table table-hover mt-4">
    <thead>
      <tr>
        <th scope="col">id</th>
        
        
        <th scope="col">title</th>
        <th scope="col">status</th>
        <th scope="col">category</th>
        <th scope="col">actions</th>
      </tr>
    </thead>
    <tbody>
    @foreach ($articles as $article)
      <tr>
        <td>{{ $article->id }}</td>
        <td>{{ $article->title }}</td>
        <td>
          @if ($article->isPublic())
            <span class="badge bg-success">published</span>
          @else
            <span class="badge bg-warning text-dark">hidden</span>
          @endif
        </td>
        <td>
          @if (is_null($article->category))
            <span class="fw-bold fst-italic">NULL</span>
          @else
            <a href="{{ route('admin.categories.show', ['category' => $article->category]) }}">{{ $article->category->name }}</a>
          @endif
        </td>
        <td>
          <a class="btn btn-primary" href="{{ route('admin.articles.show', ['article' => $article]) }}">show</a>
          <a class="btn btn-primary" href="{{ route('admin.articles.edit', ['article' => $article]) }}">edit</a>
          <a class="btn btn-primary" href="{{ route('article.show', ['year' => $article->created_at->year, 'month' => $article->created_at->month, 'day' => $article->created_at->day, 'slug' => $article->slug]) }}">Front</a>
        </td>
      </tr>
    @endforeach
    </tbody>
  </table>
  {{ $articles->links() }}
@endsection

resources/views/admin/articles/show.blade.php
@extends('layouts.admin')

@section('title', 'Show article')

@section('content')
  <x-admin-breadcrumb levels=2 label="Articles" label2="Show" link="{{ route('admin.articles.index') }}"/>
  
  <h1 class="h2">{{ $article->title }}</h1>
  
  <div class="btn-group btn-group-lg my-4">
    <a href="{{ route('admin.articles.edit', ['article' => $article]) }}" type="button" class="btn btn-primary">EDIT</a>
    @if ($article->isPublic())
      <a href="{{ route('admin.articles.hide', ['article' => $article]) }}" type="button" class="btn btn-warning" onclick="event.preventDefault(); 
        document.getElementById('hide-form').submit();">HIDE</a>
    @else
      <a href="{{ route('admin.articles.publish', ['article' => $article]) }}" type="button" class="btn btn-success" onclick="event.preventDefault(); 
        document.getElementById('publish-form').submit();">PUBLISH</a>
    @endif
    <a href="{{ route('admin.articles.destroy', ['article' => $article]) }}" type="button" class="btn btn-danger" onclick="event.preventDefault(); 
      document.getElementById('destroy-form').submit();">DELETE</a>
    <a href="{{ route('article.show', ['year' => $article->created_at->year, 'month' => $article->created_at->month, 'day' => $article->created_at->day, 'slug' => $article->slug]) }}" type="button" class="btn btn-primary">FRONT</a>
  </div>
  
  <div class="hidden">
    <form id="publish-form" action="{{ route('admin.articles.publish', ['article' => $article]) }}" method="POST">
      @method('PATCH')
      @csrf
    </form>
    <form id="hide-form" action="{{ route('admin.articles.hide', ['article' => $article]) }}" method="POST">
      @method('PATCH')
      @csrf
    </form>
    <form id="destroy-form" action="{{ route('admin.articles.destroy', ['article' => $article]) }}" method="POST">
      @method('DELETE')
      @csrf
    </form>
  </div>
    
  <ul>
    <li><strong>key:</strong> {{ $article->key }}</li>
    <li><strong>created_at:</strong> {{ $article->created_at }}</li>
    <li><strong>updated_at:</strong> {{ $article->updated_at }}</li>
    <li><strong>Public:</strong> {{ $article->public }}</li>
    <li><strong>published_at:</strong> {{ $article->published_at }}</li>
    <li><strong>Author:</strong> <a href="{{ route('admin.authors.show', ['author' => $article->author]) }}">{{ $article->author->name }}</a></li>
    <li>
      @if (is_null($article->category))
        <strong>Category:</strong> <span class="fw-bold fst-italic">NULL</span>
      @else
        <strong>Category:</strong> <a href="{{ route('admin.categories.show', ['category' => $article->category]) }}">{{ $article->category->name }}</a>
      @endif
    </li>
    <li><strong>Title:</strong> {{ $article->title }}</li>
    <li><strong>Slug:</strong> {{ $article->slug }}</li>
    <li><strong>Tags:</strong>
      <ul>
        @foreach ($article->tags as $tag)
          <li><a href="{{ route('admin.tags.show', ['tag' => $tag]) }}">{{ $tag->name }}</a></li>
        @endforeach
      </ul>
    </li>
  </ul>
  
  <figure class="figure">
    <img class="figure-img img-fluid rounded" src="{{ $article->image->url }}">
    <figcaption class="figure-caption">{{ $article->image->credit }}</figcaption>
  </figure>
  <div>{!! $contentInHtml !!}</div>
  
  <div class="border-top pt-4">
    <h3 class="h3">
      <span>{{ $article->comments->count() }}</span> comments
    </h3>
    <div class="">
      @foreach ($article->comments as $comment)
        <div class="d-flex flex-row mt-3">
          <div class="comment-author-thumbnail">
            <a href="{{ route('admin.users.show', ['user' => $comment->author]) }}">
              <img class="rounded-circle" src="https://via.placeholder.com/50" alt="">
            </a>
          </div>
          <div class="comment-main flex-grow-1 ms-3">
            <div class="d-flex">
              <div class="flex-shrink-1">
                <a href="{{ route('admin.users.show', ['user' => $comment->author]) }}">{{ $comment->author->name }}</a>
              </div>
              <div class="ms-3">{{ $comment->created_at }}</div>
            </div>
            <div class="">
              {{ $comment->content }}
            </div>
          </div>
        </div>
      @endforeach
    </div>
  </div>
@endsection